# Generated by Django 5.1.6 on 2025-03-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(default='msdms'),
            preserve_default=False,
        ),
    ]
