# Generated by Django 5.1.6 on 2025-03-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_socialmedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='photo',
            field=models.ImageField(default='asdfg', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
