# Generated by Django 5.1.6 on 2025-03-20 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_myinformation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='about.myinformation'),
            preserve_default=False,
        ),
    ]
